package cn.yhd.entity;

import java.util.Date;

public class IllegalSelfie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_selfie.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_selfie.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_selfie.url_encode
     *
     * @mbggenerated
     */
    private String urlEncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_selfie.remake
     *
     * @mbggenerated
     */
    private String remake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_selfie.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_selfie.post_id
     *
     * @mbggenerated
     */
    private Long postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_selfie.admin_id
     *
     * @mbggenerated
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_selfie.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_selfie.id
     *
     * @return the value of illegal_selfie.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_selfie.id
     *
     * @param id the value for illegal_selfie.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_selfie.url
     *
     * @return the value of illegal_selfie.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_selfie.url
     *
     * @param url the value for illegal_selfie.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_selfie.url_encode
     *
     * @return the value of illegal_selfie.url_encode
     *
     * @mbggenerated
     */
    public String getUrlEncode() {
        return urlEncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_selfie.url_encode
     *
     * @param urlEncode the value for illegal_selfie.url_encode
     *
     * @mbggenerated
     */
    public void setUrlEncode(String urlEncode) {
        this.urlEncode = urlEncode == null ? null : urlEncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_selfie.remake
     *
     * @return the value of illegal_selfie.remake
     *
     * @mbggenerated
     */
    public String getRemake() {
        return remake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_selfie.remake
     *
     * @param remake the value for illegal_selfie.remake
     *
     * @mbggenerated
     */
    public void setRemake(String remake) {
        this.remake = remake == null ? null : remake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_selfie.user_id
     *
     * @return the value of illegal_selfie.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_selfie.user_id
     *
     * @param userId the value for illegal_selfie.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_selfie.post_id
     *
     * @return the value of illegal_selfie.post_id
     *
     * @mbggenerated
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_selfie.post_id
     *
     * @param postId the value for illegal_selfie.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_selfie.admin_id
     *
     * @return the value of illegal_selfie.admin_id
     *
     * @mbggenerated
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_selfie.admin_id
     *
     * @param adminId the value for illegal_selfie.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_selfie.create_time
     *
     * @return the value of illegal_selfie.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_selfie.create_time
     *
     * @param createTime the value for illegal_selfie.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}