package cn.yhd.entity;

public class UserFunctionAuthKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_function_auth.function_code
     *
     * @mbggenerated
     */
    private Byte functionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_function_auth.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_function_auth.function_code
     *
     * @return the value of user_function_auth.function_code
     *
     * @mbggenerated
     */
    public Byte getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_function_auth.function_code
     *
     * @param functionCode the value for user_function_auth.function_code
     *
     * @mbggenerated
     */
    public void setFunctionCode(Byte functionCode) {
        this.functionCode = functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_function_auth.user_id
     *
     * @return the value of user_function_auth.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_function_auth.user_id
     *
     * @param userId the value for user_function_auth.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}