package cn.yhd.dao;

import cn.yhd.entity.UserFunctionAuth;
import cn.yhd.entity.UserFunctionAuthExample;
import cn.yhd.entity.UserFunctionAuthKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFunctionAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int countByExample(UserFunctionAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int deleteByExample(UserFunctionAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserFunctionAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int insert(UserFunctionAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int insertSelective(UserFunctionAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    List<UserFunctionAuth> selectByExample(UserFunctionAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    UserFunctionAuth selectByPrimaryKey(UserFunctionAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserFunctionAuth record, @Param("example") UserFunctionAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserFunctionAuth record, @Param("example") UserFunctionAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserFunctionAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_function_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserFunctionAuth record);
}